language: bash
services: docker

env:
  - VERSION=2.7 VARIANT=buster
  - VERSION=2.7 VARIANT=buster/slim
  - VERSION=2.7 VARIANT=alpine3.12
  - VERSION=2.7 VARIANT=alpine3.10
  - VERSION=2.3 VARIANT=stretch
  - VERSION=2.3 VARIANT=stretch/slim

install:
  - git clone --depth 1 https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "$VERSION/$VARIANT"
  - slash='/'; image="ruby:${VERSION}-${VARIANT//$slash/-}"

script:
  - |
    (
      set -Eeuo pipefail
      set -x
      travis_retry docker build -t "$image" .
      ~/official-images/test/run.sh "$image"
    )

after_script:
  - docker images
# vim:set et ts=2 sw=2:
