name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Azure Container Registry Login
      uses: Azure/docker-login@v1
      with:
        # Container registry username
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }} 
        login-server: acrerepassageneric.azurecr.io
    
    - name: Build Ruby 2.3-jessie
      run: |
        docker build . --file 2.3/jessie/Dockerfile --tag 2.3-jessie
        docker push acrerepassageneric.azurecr.io/ruby-alpine-jemalloc-locale:2.3-jessie

    - name: Build Ruby 2.3-stretch
      run: |
        docker build . --file 2.3/stretch/Dockerfile --tag 2.3-stretch
        docker push acrerepassageneric.azurecr.io/ruby-alpine-jemalloc-locale:2.3-stretch

    - name: Build Ruby 2.7-alpine3.11
      run: |
        docker build . --file 2.7/alpine3.11/Dockerfile --tag 2.7-alpine3.11
        docker push acrerepassageneric.azurecr.io/ruby-alpine-jemalloc-locale:2.7-alpine3.11

    - name: Build Ruby 2.7-alpine3.12
      run: |
        docker build . --file 2.7/alpine3.12/Dockerfile --tag 2.7-alpine3.12
        docker push acrerepassageneric.azurecr.io/ruby-alpine-jemalloc-locale:2.7-alpine3.12

    - name: Build Ruby 2.7-buster
      run: |
        docker build . --file 2.7/buster/Dockerfile --tag 2.7-buster
        docker push acrerepassageneric.azurecr.io/ruby-alpine-jemalloc-locale:2.7-buster

    - name: Build Ruby 2.7-buster-slim
      run: |
        docker build . --file 2.7/buster/slim/Dockerfile --tag 2.7-buster-slim
        docker push acrerepassageneric.azurecr.io/ruby-alpine-jemalloc-locale:2.7-buster-slim
